name: Simple pipeline

on:
  push:
    branches:
      - main

jobs:
  plan_terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Plan acceptance
        run: |
          terraform init
          terraform apply -auto-approve
          cat debug.txt

      - name: Save Terraform plan as artifact file
        uses: actions/upload-artifact@v3
        with:
          name: plan-file
          path: |
            debug.txt
  apply_terraform:
    runs-on: ubuntu-latest
    needs: plan_terraform
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: plan-file

      - name: apply everything
        run: |
          cat debug.txt
          terraform init
          terraform apply -auto-approve
          cat debug.txt
          
