name: production pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  check_for_changes:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check if skeleton has changes
        uses: dorny/paths-filter@v2
        id: check_changes
        with:
          filters: |
            skeleton:
              - 'stacks/skeleton/**'
            app1:
              - 'stacks/skeleton/**'
              - 'stacks/infra/app1/**'
            app2:
              - 'stacks/skeleton/**'
              - 'stacks/infra/app2/**'

  plan_terraform_skeleton_production:
    runs-on: ubuntu-latest
    needs: check_for_changes
    if: steps.check_for_changes.outputs.skeleton == 'true'
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: plan skeleton
        run: |
          cd stacks/skeleton/base-networking
          terraform init
          terraform plan -out=base-networking.tfplan


      - name: Save Terraform plan as artifact file
        uses: actions/upload-artifact@v3
        with:
          name: plan-files-skeleton
          path: |
            stacks/skeleton/**/*tfplan

  apply_terraform_skeleton_production:
    runs-on: ubuntu-latest
    needs: plan_terraform_skeleton_production
    if: steps.check_for_changes.outputs.skeleton == 'true'
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check if skeleton has changes
        uses: dorny/paths-filter@v2
        id: skeleton_has_changes
        with:
          filters: |
            skeleton:
              - 'stacks/skeleton/**'

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: plan-files-skeleton

      - name: apply everything
        run: |
          cd stacks/skeleton/base-networking
          terraform init
          terraform apply -auto-approve base-networking.tfplan

  plan_terraform_app1_production:
    runs-on: ubuntu-latest
    if: steps.check_for_changes.outputs.skeleton == 'true' || steps.check_for_changes.outputs.app1 == 'true'
    needs:
      - plan_terraform_skeleton_production
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: plan skeleton
        run: |
          cd stacks/infra/app1
          echo "Running plan in app1"
          terraform init
          terraform plan -out=app1.tfplan
        with:
          filters: |
            skeleton:
              - 'stacks/skeleton/**'
              - 'stacks/app1/**'

      - name: Save Terraform plan as artifact file
        uses: actions/upload-artifact@v3
        with:
          name: plan-files-app1
          path: |
            stacks/app1/*tfplan

  apply_terraform_app1_production:
    runs-on: ubuntu-latest
    if: steps.check_for_changes.outputs.skeleton == 'true' || steps.check_for_changes.outputs.app1 == 'true'
    needs: plan_terraform_app1_production
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: plan-files-app1

      - name: apply everything
        run: |
          cd stacks/infra/app1
          echo "Running apply in app1"
          stat app1.tfplan

  plan_terraform_app2_production:
    runs-on: ubuntu-latest
    if: steps.check_for_changes.outputs.skeleton == 'true' || steps.check_for_changes.outputs.app2 == 'true'
    needs:
      - plan_terraform_skeleton_production
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: plan skeleton
        run: |
          cd stacks/infra/app2
          echo "Running plan in app2"
          terraform init
          terraform plan -out=app2.tfplan
        with:
          filters: |
            skeleton:
              - 'stacks/skeleton/**'
              - 'stacks/app2/**'

      - name: Save Terraform plan as artifact file
        uses: actions/upload-artifact@v3
        with:
          name: plan-files-app2
          path: |
            stacks/app2/*tfplan

  apply_terraform_app2_production:
    runs-on: ubuntu-latest
    needs: plan_terraform_app2_production
    if: steps.check_for_changes.outputs.skeleton == 'true' || steps.check_for_changes.outputs.app2 == 'true'
    container:
      image: hashicorp/terraform:1.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: plan-files-app2

      - name: apply everything
        run: |
          cd stacks/infra/app2
          echo "Running apply in app2"
          stat app2.tfplan
